/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#001e2c",
        "on-primary-fixed-variant": "#38485d",
        "on-surface": "#E2E2E2",
        "on-secondary": "#0a315b",
        "outline": "#8e9197",
        "surface-container-low": "#1a1c1e",
        "on-secondary-fixed": "#001c3b",
        "secondary-fixed-dim": "#a9c8fb",
        "primary-fixed-dim": "#b8c8e1",
        "surface-variant": "#333537",
        "error": "#ffb4ab",
        "secondary-fixed": "#d5e3ff",
        "background": "#121416",
        "primary-fixed": "#d4e4fe",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#0c1c2f",
        "inverse-surface": "#e2e2e5",
        "on-tertiary-fixed-variant": "#264b5e",
        "on-error": "#690005",
        "on-surface-variant": "#C4C7C5",
        "tertiary-fixed-dim": "#a7cbe3",
        "surface-container": "#1e2022",
        "on-tertiary-container": "#45687d",
        "on-primary-container": "#56657b",
        "on-tertiary": "#0a3447",
        "surface-container-lowest": "#0c0e10",
        "success-tonal": "#C4EED0",
        "tertiary": "#fffeff",
        "on-secondary-container": "#98b7e9",
        "error-tonal": "#F2B8B5",
        "primary-container": "#d3e3fd",
        "inverse-primary": "#505f75",
        "surface-container-high": "#282a2c",
        "on-secondary-fixed-variant": "#274773",
        "tertiary-container": "#c2e7ff",
        "outline-variant": "#44474c",
        "surface-container-highest": "#333537",
        "surface-tint": "#b8c8e1",
        "primary": "#fffeff",
        "secondary-container": "#274773",
        "tertiary-fixed": "#c3e7ff",
        "warning-tonal": "#FFE082",
        "surface-dim": "#121416",
        "on-primary": "#223145",
        "inverse-on-surface": "#2f3133",
        "surface": "#121416",
        "error-container": "#93000a",
        "on-background": "#e2e2e5",
        "surface-bright": "#37393b",
        "secondary": "#a9c8fb",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "panel-sidebar": "360px",
        "margin-desktop": "1.5rem",
        "unit-sm": "8px",
        "margin-mobile": "1rem",
        "unit-lg": "24px",
        "unit-md": "16px",
        "gutter": "1rem",
        "unit-xs": "4px",
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        "headline-sm": ["Inter"],
        "label-sm": ["JetBrains Mono"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "title-lg": ["Inter"],
        "display-lg": ["Inter"],
        "label-md": ["JetBrains Mono"],
      },
      fontSize: {
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.5px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0.25px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0.5px", fontWeight: "400" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "400" }],
        "title-lg": ["22px", { lineHeight: "28px", fontWeight: "500" }],
        "display-lg": ["57px", { lineHeight: "64px", letterSpacing: "-0.25px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.5px", fontWeight: "500" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
