# Generated by Django 5.2.17 on 2026-08-18 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("simulation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterventionCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intervention_type",
                    models.CharField(
                        choices=[
                            ("VEHICLE_REROUTING", "Vehicle Rerouting"),
                            ("SCHEDULE_MODIFICATION", "Schedule Modification"),
                            ("SPARE_DEPLOYMENT", "Spare Vehicle Deployment"),
                            ("EMERGENCY_SHUTTLE", "Emergency Shuttle Deployment"),
                            ("FREQUENCY_ADJUSTMENT", "Service Frequency Adjustment"),
                            ("VEHICLE_REDISTRIBUTION", "Vehicle Redistribution"),
                            ("STOP_CLOSURE", "Temporary Stop Closure"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Extensible JSON for specific intervention details",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("EVALUATED", "Evaluated"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="simulation.simulationscenario",
                    ),
                ),
            ],
        ),
    ]
