# Generated by Django 5.2.17 on 2026-08-18 09:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operator_identifier", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("scenario_id", models.IntegerField(blank=True, null=True)),
                ("intervention_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "transport_type",
                    models.CharField(
                        choices=[("BUS", "Bus"), ("METRO", "Metro"), ("TRAM", "Tram")],
                        default="BUS",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("lat", models.FloatField(default=0.0)),
                ("lon", models.FloatField(default=0.0)),
                ("is_accessible", models.BooleanField(default=True)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Maximum passenger queue capacity"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometry",
                    models.JSONField(
                        default=list,
                        help_text="List of [lon, lat] coordinates representing a LineString",
                    ),
                ),
                (
                    "distance",
                    models.FloatField(
                        help_text="Distance in meters",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "baseline_travel_time",
                    models.FloatField(
                        help_text="Time in seconds",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "baseline_cost",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("is_accessible", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="core.stop",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="core.stop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Disruption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disruption_type", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField()),
                ("expected_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "affected_edge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.edge",
                    ),
                ),
                (
                    "affected_stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.stop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=100, unique=True)),
                ("vehicle_type", models.CharField(max_length=50)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("occupancy", models.PositiveIntegerField(default=0)),
                ("capacity", models.PositiveIntegerField()),
                ("accessible_capacity", models.PositiveIntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DELAYED", "Delayed"),
                            ("BROKEN", "Broken"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="INACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.route",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RouteEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_order", models.PositiveIntegerField()),
                (
                    "edge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_by_routes",
                        to="core.edge",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_edges",
                        to="core.route",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("route", "edge"), name="unique_route_edge"
                    ),
                    models.UniqueConstraint(
                        fields=("route", "sequence_order"), name="unique_route_order"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="edge",
            constraint=models.UniqueConstraint(
                fields=("source", "target"), name="unique_edge_direction"
            ),
        ),
        migrations.AddConstraint(
            model_name="edge",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", models.F("target")), _negated=True),
                name="prevent_self_referencing_edge",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(("occupancy__lte", models.F("capacity"))),
                name="occupancy_lte_capacity",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(("accessible_capacity__lte", models.F("capacity"))),
                name="accessible_capacity_lte_capacity",
            ),
        ),
    ]
