# Generated by Django 5.2.17 on 2026-08-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditlog",
            name="intervention_id",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="candidate_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="previous_state_reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="resulting_state_reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="energy_rate_kwh_per_km",
            field=models.FloatField(default=1.2, help_text="Energy consumption per km"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="scenario_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
