# Generated by Django 5.2.17 on 2026-08-19 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_auditlog_intervention_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="edge",
            name="current_traffic_speed",
            field=models.FloatField(
                default=10.0, help_text="Current live traffic speed in m/s"
            ),
        ),
        migrations.AddField(
            model_name="edge",
            name="free_flow_speed",
            field=models.FloatField(default=10.0, help_text="Free flow speed in m/s"),
        ),
        migrations.AddField(
            model_name="edge",
            name="last_traffic_update",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
