# Generated by Django 5.2.17 on 2026-08-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_edge_current_traffic_speed_edge_free_flow_speed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="edge",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
