# Generated by Django 5.2.17 on 2026-08-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_edge_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="disruption",
            name="provider_incident_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="disruption",
            name="source",
            field=models.CharField(
                choices=[
                    ("OPERATOR", "Operator"),
                    ("EXTERNAL", "External"),
                    ("SIMULATION", "Simulation"),
                ],
                default="OPERATOR",
                max_length=20,
            ),
        ),
    ]
