# Generated by Django 5.2.17 on 2026-08-20 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_disruption_provider_incident_id_disruption_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edge',
            old_name='last_traffic_update',
            new_name='last_updated_at',
        ),
        migrations.AddField(
            model_name='disruption',
            name='data_source',
            field=models.CharField(choices=[('TOMTOM', 'TomTom API'), ('CRUT', 'CRUT Telemetry'), ('SIMULATION', 'Simulation Engine'), ('ESTIMATED', 'Estimated/Fallback')], default='OPERATOR', max_length=20),
        ),
        migrations.AddField(
            model_name='disruption',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='disruption',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 20, 9, 0, 6, 257010, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edge',
            name='data_source',
            field=models.CharField(choices=[('TOMTOM', 'TomTom API'), ('CRUT', 'CRUT Telemetry'), ('SIMULATION', 'Simulation Engine'), ('ESTIMATED', 'Estimated/Fallback')], default='ESTIMATED', max_length=20),
        ),
        migrations.AddField(
            model_name='edge',
            name='received_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
