# Generated by Django 5.2.17 on 2026-08-18 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intervention_id", models.IntegerField()),
                ("is_feasible", models.BooleanField(default=True)),
                ("delay_metrics", models.JSONField(blank=True, default=dict)),
                ("waiting_time_metrics", models.JSONField(blank=True, default=dict)),
                ("crowding_metrics", models.JSONField(blank=True, default=dict)),
                ("energy_metrics", models.JSONField(blank=True, default=dict)),
                ("accessibility_metrics", models.JSONField(blank=True, default=dict)),
                ("operational_cost", models.FloatField(default=0.0)),
                ("additional_metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="SimulationScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIALIZED", "Initialized"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="INITIALIZED",
                        max_length=20,
                    ),
                ),
                (
                    "snapshot_timestamp",
                    models.DateTimeField(
                        help_text="The timestamp of the live state this scenario cloned"
                    ),
                ),
                (
                    "base_disruption",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.disruption",
                    ),
                ),
            ],
        ),
    ]
